### ISSUE TITLE
xsd.Int it's managed? Value '1' for class 'String'

### ISSUE THREAD

**Issue by vpistis** [FlightDataServices/soapfish#18]
Hi,
i'm a newbie in SOAP and I found this great project very very interesting! Is very simple create python server/client code using a wsdl file.

But, I found some problem, but this in the title is the most important, actually.
I have a wsdl that i used it for generate python server code in some manner...the wsdl2py doesn't run correctly...
Calling the url to service dispatcher with parameter "?wsdl", this error appear:

`Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/soapbox/soap.py", line 262, in django_dispatch
    wsdl = py2wsdl.generate_wsdl(service)
  File "/Library/Python/2.7/site-packages/soapbox/py2wsdl.py", line 132, in generate_wsdl
    build_types(wsdl, definitions, service.schema)
  File "/Library/Python/2.7/site-packages/soapbox/py2wsdl.py", line 123, in build_types
    xsd_schema = generate_xsdspec(schema)
  File "/Library/Python/2.7/site-packages/soapbox/py2xsd.py", line 197, in generate_xsdspec
    xsd_ct = xsd_complexType(ct)
  File "/Library/Python/2.7/site-packages/soapbox/py2xsd.py", line 148, in xsd_complexType
    xsd_element = create_xsd_element(element)
  File "/Library/Python/2.7/site-packages/soapbox/py2xsd.py", line 84, in create_xsd_element
    xsd_element.maxOccurs = element._maxOccurs
  File "/Library/Python/2.7/site-packages/soapbox/xsd.py", line 916, in __setattr__
    super(ComplexType, self).__setattr__(attr, field.accept(value))
  File "/Library/Python/2.7/site-packages/soapbox/xsd.py", line 578, in accept
    return self._type.accept(value)
  File "/Library/Python/2.7/site-packages/soapbox/xsd.py", line 243, in accept
    raise ValueError("Value '%s' for class '%s'." % (unicode(value), self.__class__.__name__))
ValueError: Value '1' for class 'String'.

`

I have changed the file xsd.py at row number 240 by adding this code: 
`        if isinstance(value, int):
            value = unicode(value)
`
and then the exception doesn't appear, but a new one error appears:
`
<faultstring>Element '{urn:PayBemoovListener}notifyResponse': No matching global declaration available for the validation root.</faultstring>
`

It's possible that soapbox not managing values that are not strings?I have integers values in my types.
This is the wsdl example that i use: https://drive.google.com/file/d/0B0uiGluEWZlOcU1aRzJ3OUs2ZXM/view?usp=sharing

Help me if is possible :)

Thanx
Vale

**Comment by pope1ni** [comment]
Closing as soapbox has been superseded by soapfish where this issue looks to have been fixed.
