### ISSUE TITLE
wsdl2py: import error.

### ISSUE THREAD

**Issue by unk2k** [FlightDataServices/soapfish#23]
wsdl —> http://slednev.ru/example.wsdl

 # wsdl2py -c 'http://slednev.ru/example.wsdl'
```
Traceback (most recent call last):
  File "/usr/local/bin/wsdl2py", line 9, in <module>
    load_entry_point('Soapbox==0.3.7', 'console_scripts', 'wsdl2py')()
  File "/usr/local/lib/python2.7/site-packages/soapbox/wsdl2py.py", line 133, in main
    print generate_code_from_wsdl(xml, 'client')
  File "/usr/local/lib/python2.7/site-packages/soapbox/wsdl2py.py", line 99, in generate_code_from_wsdl
    is_server=bool(target == 'server'),
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/soapbox/templates/wsdl", line 60, in top-level template code
    input={{ inputMessage.part.type|remove_namespace|capitalize }},
  File "/usr/local/lib/python2.7/site-packages/soapbox/utils.py", line 72, in capitalize
    return value[0].upper() + value[1:]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

```>>>  soapbox.__version__```
'0.3.7'

```# uname -a```
Darwin xxl 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

![why](https://cloud.githubusercontent.com/assets/114572/8659150/62fc52c8-29b1-11e5-97fd-c927552f6024.jpg)

**Comment by tjetzinger** [comment]
Have the exact same issue..

**Comment by FelixSchwarz** [comment]
Unfortunately with soapfish I get a different error with the WSDL above:

    ValueError: ('expected exactly one part', 'GetManufacturerListMessage', [])

However it seems the  soapfish code does a bit more so maybe it is easy to fix?

**Comment by pope1ni** [comment]
The soapbox project has now been retired in favour of the soapfish project. I can confirm what @felixschwarz says in his comment. A new issue has been created: felixschwarz/soapfish#75
